dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - secure: EdhgS8Gk5rqgrNVmkw0YHNgNhTjV4kTZ9RpKk/tfqAAVblfpONHH+dEnQhmPgKSfzDCkVHGc4BMp/3WIHkOP+0kPYXgIbC6MbtBI2bwfnc8YZk3y+aqUJP4sE59uw/SPQubaY+qSJQK9nO9ozXZctwEMJZBxuU4NxDPSK/O8SSVSdKi4mjbJUA+RRJotUIUTT0yBwiqybqft1UBaFggZQwWRIEgBoLbgrvjcEN7UNJZD10dj/5tNQRINRBJd2B7CLiUtyoKubtSw4c4CJ7nlIqmIkKy9p7EYmIfgfzo9G/XGug50Mf23bUf5KRo3V1h/MC7dYrfiSseqt80y5W/ngeX+8lrAjrTZCQyvA+YZilp4iTXGMA0wQ9DBF666YNHCROKMb21rlAInE00yIZNTcZ+jq8ArCJ7S+ckawf0ME7ZDEFelfi/lq7RtKj28c5qi37yD4SX5xgzVXachvQ+f9oCj+mmpiykga0u4UoY4AYgH6+VPNA/czk+5VOQ4w3SXymWHJSBJjfLg//NjGXpuhvlupnfWi61xlCI85NjbFYl+5PBb8p1Q5zg2Pn586UA378kVM7Nrs1taiR0QM6RMSqTpd80XVUrmY5rHoNzT2oFEu2BszUOgkGMQuOiOBk0lskmKSZi5i8FoDCVHTgksCyCxwbiGn3XWb38RjzR4Z/M=
  - secure: Z1mwVcKxEUy+mEB13zZLteaj2x2FYrtnFnSPbOlwMIhJGDHKFaYN45++1+GpLi7vHQEnYPEvsZfGLqqhWfjqOoPvHWsgwB1AgOLW5qZwbaOYjquxhCOpfHFu3/KWWah2A1/J1c9/dFq+cMQZzQw0ATWBJQ3f4hsB884RPqKa5y4/VNgTYfJgUHvCZ8E1QJMKDNDoX0zkXw1FMwhtcO5jLlGRiVyDzUKCakm8zewqKgYyZL635lYeziZdn+W2YuJm2uEV3qWMZKzCN7P0a4iToNJGxX9tkGOIboQF8drK3L8qmTmrPsio2VwlYqZAEWNo2qUVBXSsUsWpKDrHDQzE32ARGrj/aZM3Jip3/oX8u0PxYsZtlIYJj6KCMvyu8VkoKLQqm8CJQHX/FWkciVcqLPZeW0Ci2NO+ZdBk4uQmSv6VI3wkOvhO+00PTbhtPUpty8tNQPBrjazeoIleYG2665rUSiwbZaUxLdLKkxpTccbP3i5Sp4TWb3zKq8cQY+NxyQBb/UzwnXoV0D2j33Q0RgJNxxGw61DQjolm5Bbyekzip5HePhsC5yQSE+HI1qePR5dOuia8cUBLSeGFFm//VN2QiJs7SWZLTL8e3RzmyhFNXKRdCu75YKWses2w+nP5wlSl/+sHGA0Lvcsex3A9gEv/vubURu1sghiJxcY3LLY=
  - secure: QsBqQ1GDgqf4U7mMKQqDbfdM5Bf81qu/uwgGmBpdydDPW619k/3WGPZz4esJ1gyhZbLXQMnHG3hn3MjqMPUpI8JYdSWM4GuVxG9j5ZiXPfVjyOPsLOHyGqqkiQcCXWWphrnV6SySQl4ba+PAYwlEIJ+cnUlyAk3Sr66+FoJdfHBX5gtx54WmkP64py+yszAVMBYpn9+ZbPEC9gZ+tn35z7mAFoMcUzrdAgwJYpDabmfip1+fmOpzCdAv83CTd3buPvqv/QFduBGauOyuAz98wrJ2fQIh0+PZifp2QN8XiJXO/5JF9+F1wnY2g96N/muGQ3dh/994DLYZejOXEONo8TNnd0glB5RXb7Nc74upkf7ZUahLo/VHzLb2a3sm05h3isOkIvxdqyGI2dCXs3pKZXPwwpXSz/YE6Z+Ku6jwHR61NjnHs/m+QPyutPLb5Sq1D1PeKdaYi20hpDrUyCLIEl8R/OJIdKRM7te5nWaDhL1FDe5KqQIOuXNLnyHU4b8i+27P9rphCISoiMxgJ5RbB+ieZwUhld8aiQmRQ7VrUH/Is7zJkLr73MbsEqjwUE69fWaN7SZdX6fzVpsSXryRa2FIVNrOJXBps6UVVLvIqVbRaj3Giacxs6/khiiwmiUPEKytQob6Q248xdPwopsA+Y+fPMfFvvYN+i19cxfmTSE=
  - secure: lgKTOp4XeVyf+30Iw4IsUwGZCS5h8lX0qlVFdqVHdsHWNA1A50dRbMy+ExfQZ8lf02tpbyRkN9ivw01l7JxyI8TDJESBI0j6wQdU0H8aPC8eAP5bpTAPU6XJKn4Llil+2kMDMq7SMMS/jveklTW39z4Gha4Nt+V7D+A0pFxpgzsymB1lPkA5+F0LRXGXFm9yZUgBgG2nhLMVCmMx/lw2prCsBRlciHHKmahCmzBARxPpZ0ySDgEzEBUu74iSP/07XT/h84ASYoCoZD+s/REq8PyLecuJItjYRtJsl6iatFZ86IjqXUmYZqNyIFw9m0V5VT6mhXrBEzrdmmW3JVRiaSrUthHMQNs6M6vsq/HWkwllms0pIsVyEiLptUg2zgR0Ha0zNjFoH00UO1F4ZY1WFyuqdF8wkLeG7IYyWCS9umznSXOliIzYci3TispY6a5qZPjzShUL6Wvi7UqyTHvYhWOyNqHqMKFSXnvP7WELyUK0jpGiGkoufgx5hhswmWygH0o1LO6brejWTJJ8CgVN1AIaKXPZWQoJJKERBo40XinEAUXoig0XzLw2KHzaxS/4AjwEB7GDVyAF8FTH3tM4i93iYTtoE92qQM78TKi+QoCQPfT5tUKyuk/PgZwaCxJFijC35t8G4d3rtwiL4n2ouv/AVbQWiL2vZ6pWx5kqT+Q=
addons:
  apt:
    packages:
    - openssl
    - gnupg
before_install:
- openssl aes-256-cbc -K $encrypted_de282c3465e2_key -iv $encrypted_de282c3465e2_iv
  -in signing.tar.enc -out signing.tar -d
- tar -xvf signing.tar
- cat secret.key | base64 --decode | gpg --import
- cat key.trust | base64 --decode | gpg --import-ownertrust
- gpg --list-keys
script: bash travis-build.bash
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: releases
  api_key:
    secure: o2eWCxgYYUsvN0w/msEjF14xwBH3qFUOrffhEOh1fgsDHgPO9IutJBVTtfx6LXqx+4S9bm+KjYzgL2Ko8lDzuLKBRBFZ+s7k9CIGW1lLFfA7u1nW/lUhXI25M0LZBEZ0pmjRqRWX42T+VSdugu0Thc2UAJyd/47/h5E6o2tsOnB2Tzz0/sw7hSnPESRk4jTEEUFHZ+7uXKSobKb2pwWiSFOFpiCawNPDtTV0gtucrjjtU7dn28XEQXzAkEekXOmH4QsrtKiFKOGzYMZB3nHHuali6SQ2s3Beb0VgKk5hmtixCQ2A9XD+oTWrHiQFv4PnEANepSgjg9FkZpJuWBmX4c6SPCh8IrKiWD+NgMkR4bHodIv6A56OovUiPpfBlArLdDDefa2LFbk0JA+TTTO4TmcB9DEeRTeevrjbv3Kmth/Wa2ZSaHKMgtXJ/DNillDdTN0V1gv4G29xHkfXz6TUSgbvMOV6Sh7q2G0yJ+kZeZvBXbp3CDKkaqDFAIPf1CWULLnoHf9aWdzb7+zL64G1xiBj1eOtFgINMVsNXCAaBsQQOMZ4ZXajT5nHM3YsC0j2WDnzXxCEvnNNnaQzvnXqR6jlXa7arbw7X0PiBFJGNloprXw9Ifs/GF66yNan2pab7aBJOtS/MHjFloayi6hiG3su2AU9wd9N09F5Digrxt8=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
