dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - secure: EdhgS8Gk5rqgrNVmkw0YHNgNhTjV4kTZ9RpKk/tfqAAVblfpONHH+dEnQhmPgKSfzDCkVHGc4BMp/3WIHkOP+0kPYXgIbC6MbtBI2bwfnc8YZk3y+aqUJP4sE59uw/SPQubaY+qSJQK9nO9ozXZctwEMJZBxuU4NxDPSK/O8SSVSdKi4mjbJUA+RRJotUIUTT0yBwiqybqft1UBaFggZQwWRIEgBoLbgrvjcEN7UNJZD10dj/5tNQRINRBJd2B7CLiUtyoKubtSw4c4CJ7nlIqmIkKy9p7EYmIfgfzo9G/XGug50Mf23bUf5KRo3V1h/MC7dYrfiSseqt80y5W/ngeX+8lrAjrTZCQyvA+YZilp4iTXGMA0wQ9DBF666YNHCROKMb21rlAInE00yIZNTcZ+jq8ArCJ7S+ckawf0ME7ZDEFelfi/lq7RtKj28c5qi37yD4SX5xgzVXachvQ+f9oCj+mmpiykga0u4UoY4AYgH6+VPNA/czk+5VOQ4w3SXymWHJSBJjfLg//NjGXpuhvlupnfWi61xlCI85NjbFYl+5PBb8p1Q5zg2Pn586UA378kVM7Nrs1taiR0QM6RMSqTpd80XVUrmY5rHoNzT2oFEu2BszUOgkGMQuOiOBk0lskmKSZi5i8FoDCVHTgksCyCxwbiGn3XWb38RjzR4Z/M=
  - secure: Z1mwVcKxEUy+mEB13zZLteaj2x2FYrtnFnSPbOlwMIhJGDHKFaYN45++1+GpLi7vHQEnYPEvsZfGLqqhWfjqOoPvHWsgwB1AgOLW5qZwbaOYjquxhCOpfHFu3/KWWah2A1/J1c9/dFq+cMQZzQw0ATWBJQ3f4hsB884RPqKa5y4/VNgTYfJgUHvCZ8E1QJMKDNDoX0zkXw1FMwhtcO5jLlGRiVyDzUKCakm8zewqKgYyZL635lYeziZdn+W2YuJm2uEV3qWMZKzCN7P0a4iToNJGxX9tkGOIboQF8drK3L8qmTmrPsio2VwlYqZAEWNo2qUVBXSsUsWpKDrHDQzE32ARGrj/aZM3Jip3/oX8u0PxYsZtlIYJj6KCMvyu8VkoKLQqm8CJQHX/FWkciVcqLPZeW0Ci2NO+ZdBk4uQmSv6VI3wkOvhO+00PTbhtPUpty8tNQPBrjazeoIleYG2665rUSiwbZaUxLdLKkxpTccbP3i5Sp4TWb3zKq8cQY+NxyQBb/UzwnXoV0D2j33Q0RgJNxxGw61DQjolm5Bbyekzip5HePhsC5yQSE+HI1qePR5dOuia8cUBLSeGFFm//VN2QiJs7SWZLTL8e3RzmyhFNXKRdCu75YKWses2w+nP5wlSl/+sHGA0Lvcsex3A9gEv/vubURu1sghiJxcY3LLY=
  - secure: QsBqQ1GDgqf4U7mMKQqDbfdM5Bf81qu/uwgGmBpdydDPW619k/3WGPZz4esJ1gyhZbLXQMnHG3hn3MjqMPUpI8JYdSWM4GuVxG9j5ZiXPfVjyOPsLOHyGqqkiQcCXWWphrnV6SySQl4ba+PAYwlEIJ+cnUlyAk3Sr66+FoJdfHBX5gtx54WmkP64py+yszAVMBYpn9+ZbPEC9gZ+tn35z7mAFoMcUzrdAgwJYpDabmfip1+fmOpzCdAv83CTd3buPvqv/QFduBGauOyuAz98wrJ2fQIh0+PZifp2QN8XiJXO/5JF9+F1wnY2g96N/muGQ3dh/994DLYZejOXEONo8TNnd0glB5RXb7Nc74upkf7ZUahLo/VHzLb2a3sm05h3isOkIvxdqyGI2dCXs3pKZXPwwpXSz/YE6Z+Ku6jwHR61NjnHs/m+QPyutPLb5Sq1D1PeKdaYi20hpDrUyCLIEl8R/OJIdKRM7te5nWaDhL1FDe5KqQIOuXNLnyHU4b8i+27P9rphCISoiMxgJ5RbB+ieZwUhld8aiQmRQ7VrUH/Is7zJkLr73MbsEqjwUE69fWaN7SZdX6fzVpsSXryRa2FIVNrOJXBps6UVVLvIqVbRaj3Giacxs6/khiiwmiUPEKytQob6Q248xdPwopsA+Y+fPMfFvvYN+i19cxfmTSE=
  - secure: ljkqGh0Gh4r6lBb1rl6ksWji4OpZrGyu2x1I5AY57uzROUrd28VzuckV/N1IrlP2+3TIr2anYGKdHTJ24LLFKRKkY6hMAkH3DAnv8W/KgI0xkYnX22iP92clkWbHlorhvjXMlAoiwsXogUanUmJjMEynwoAtz4pY8UG8hsSWYRx2wQZeRU0POQt7PJqlK6Ht8o1MrLdzqT2nY5HbulZ5wKdgHF1IEEGfTAK5SLEVtGENFQSOgR6V+2umwat31BhIFm5LPOX/HUN5+LnJVwTLklQ+v0f277gfJuDYOqWrEDNcQe6jHzYLumspN8YmdpRF9SH9k+01DLU1f2GusBE0i3MX0BnIMmHDKfjzajgUwhp4j+BCZTYDWZZ4/2PVDTDhvDb2ZBWq3AEg/eFtOKRTrtoWiGKgsOhv0oHIVPcAoaTyQA6jbNC/jN0StgHPO/BCNxScFlMtWj7UHb6WtbiCPelX1uqLvI+cgH8nNtxL/DsXAKb6ysetyIcwfBO/L3kUzuNyolyUAerLgUzkwxroEllLe/yQYF8apSa8mZWFBHuIZBAGdg/oNWT9LaHBHg368pFDgInO3YfpRlSiZw/AjqKbUQsjoBHdJyMUhSs72NaeaE8kY3wHfQFgK1Ij39eF8HQdoUm4etaSBqcOi41WlK7eA6SQJCPvQtdK1aK8eEc=
  - secure: N6YUULgoL/z49kl7MHE8c8rfacDUPTiXbVxrEjJWytij07X3wI/FaqkLdwRuy53VTJ2cgb4lvN0h3tdGmicqDLmoQH8lM67mW53yfRjLoqT/rih7gIViKlQlDcDYWCntzjxGkkV5OOICXSRCp8F87y/KYjpjEsgDGPmKwpsJtnfDSdjfYaIDvRQApd2FY5NFR9XIvXl8ggdcoyTjYF2o4BigLxzEduSyhy/39l8iN1ac/tpBzSwxEZCuiiFbxiWBpN4Q/LUKUk8ggrl2WiVg6dJZOlAUbHmaJ3DUwsX4O1qNKkPu1k7l/8+i24EDgqUmK+4pTMWt5o7zfD4+Jy7ZTGodq/MvGqUTmNpY4mCT83C/C8rGn06DaEZXctNjB9bTRhYHxGqjdCZrCWFzseS/VUjiGehRuNdBxhgeL52Ezn31s6mvgzwOSgkqZJekfwcvFlX0GC6+UdXLQWTdIATNgMAZ/gPmvIj42qtqPCWSH64ImbPvqYauVBMSXDP7Ex5CkN5xPnD/VhNQS+iw5RapsUSwMmh7V/5LkbFlFG7MYTEkLea+mSIYKMRX25BMsaRBXpNHxwgLTshLvqU6/IC/CwbJ3lR6imvGOZMyEjGRGJ5MyxKH+KLOxQLeJ+10ppmP+M8aR6cKh/qOb1NCfb34XUBH7OAOqIyJyW2Ww1t9hGo=
addons:
  apt:
    packages:
    - openssl
before_install:
- openssl aes-256-cbc -K $encrypted_de282c3465e2_key -iv $encrypted_de282c3465e2_iv
  -in atomist.keystore.enc -out atomist.keystore -d
install: true
script: bash travis-build.bash
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: releases
  api_key:
    secure: o2eWCxgYYUsvN0w/msEjF14xwBH3qFUOrffhEOh1fgsDHgPO9IutJBVTtfx6LXqx+4S9bm+KjYzgL2Ko8lDzuLKBRBFZ+s7k9CIGW1lLFfA7u1nW/lUhXI25M0LZBEZ0pmjRqRWX42T+VSdugu0Thc2UAJyd/47/h5E6o2tsOnB2Tzz0/sw7hSnPESRk4jTEEUFHZ+7uXKSobKb2pwWiSFOFpiCawNPDtTV0gtucrjjtU7dn28XEQXzAkEekXOmH4QsrtKiFKOGzYMZB3nHHuali6SQ2s3Beb0VgKk5hmtixCQ2A9XD+oTWrHiQFv4PnEANepSgjg9FkZpJuWBmX4c6SPCh8IrKiWD+NgMkR4bHodIv6A56OovUiPpfBlArLdDDefa2LFbk0JA+TTTO4TmcB9DEeRTeevrjbv3Kmth/Wa2ZSaHKMgtXJ/DNillDdTN0V1gv4G29xHkfXz6TUSgbvMOV6Sh7q2G0yJ+kZeZvBXbp3CDKkaqDFAIPf1CWULLnoHf9aWdzb7+zL64G1xiBj1eOtFgINMVsNXCAaBsQQOMZ4ZXajT5nHM3YsC0j2WDnzXxCEvnNNnaQzvnXqR6jlXa7arbw7X0PiBFJGNloprXw9Ifs/GF66yNan2pab7aBJOtS/MHjFloayi6hiG3su2AU9wd9N09F5Digrxt8=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
